<?php
/* Data sample for moduleblockadvfooter*/
$query = "CREATE TABLE IF NOT EXISTS `_DB_PREFIX_loffc_block` (
  `id_loffc_block` int(11) NOT NULL AUTO_INCREMENT,
  `width` float(10,2) NOT NULL,
  `show_title` tinyint(1) NOT NULL,
  `id_position` tinyint(2) NOT NULL,
  PRIMARY KEY (`id_loffc_block`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8;
INSERT INTO `_DB_PREFIX_loffc_block` VALUES
('1','27.00','0','2'),
('2','17.00','1','2'),
('3','17.00','1','2'),
('4','17.00','1','2'),
('13','22.00','1','2');
CREATE TABLE IF NOT EXISTS `_DB_PREFIX_loffc_block_item` (
  `id_loffc_block_item` int(11) NOT NULL AUTO_INCREMENT,
  `id_loffc_block` int(11) NOT NULL,
  `type` varchar(25) NOT NULL,
  `link` varchar(2000) NOT NULL,
  `linktype` varchar(25) NOT NULL,
  `link_content` varchar(2000) NOT NULL,
  `module_name` varchar(100) NOT NULL,
  `hook_name` varchar(100) NOT NULL,
  `latitude` varchar(25) NOT NULL,
  `longitude` varchar(25) NOT NULL,
  `addthis` tinyint(1) NOT NULL,
  `show_title` tinyint(1) NOT NULL DEFAULT '1',
  `target` varchar(20) NOT NULL DEFAULT '_self',
  `position` int(11) NOT NULL,
  PRIMARY KEY (`id_loffc_block_item`)
) ENGINE=InnoDB AUTO_INCREMENT=36 DEFAULT CHARSET=utf8;
INSERT INTO `_DB_PREFIX_loffc_block_item` VALUES
('1','4','link','','link','history','','','','','0','1','','0'),
('3','3','link','','link','prices-drop','','','','','0','1','','0'),
('14','4','link','','link','order-slip','','','','','0','1','_self','0'),
('15','4','link','','link','addresses','','','','','0','1','_self','0'),
('16','4','link','','link','identity','','','','','0','1','_self','0'),
('17','4','link','','link','discount','','','','','0','1','_self','0'),
('18','2','link','','cms','1','','','','','0','1','_self','0'),
('19','2','link','','cms','2','','','','','0','1','_self','1'),
('21','2','link','','cms','4','','','','','0','1','_self','2'),
('22','2','link','','cms','5','','','','','0','1','_self','3'),
('23','3','link','','link','new-products','','','','','0','1','_self','1'),
('24','3','link','','link','best-sales','','','','','0','1','_self','2'),
('25','3','link','','link','stores','','','','','0','1','_self','3'),
('26','3','link','','link','contact','','','','','0','1','_self','4'),
('29','1','custom_html','','','','','','','','0','0','','0'),
('30','2','link','','cms','3','','','','','0','1','_self','4'),
('31','13','module','','','','blocknewsletter','displayfooter','','','0','0','','0'),
('32','13','custom_html','','','','','','','','0','0','','0'),
('33','2','link','','cms','2','','','','','0','1','_self','5'),
('34','3','link','','cms','3','','','','','0','1','_self','5'),
('35','4','link','','cms','5','','','','','0','1','_self','1');
CREATE TABLE IF NOT EXISTS `_DB_PREFIX_loffc_block_item_lang` (
  `id_loffc_block_item` int(11) NOT NULL,
  `id_lang` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `text` text NOT NULL,
  PRIMARY KEY (`id_loffc_block_item`,`id_lang`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `_DB_PREFIX_loffc_block_item_shop` (
  `id_loffc_block_item` int(11) NOT NULL,
  `id_shop` int(11) NOT NULL,
  PRIMARY KEY (`id_loffc_block_item`,`id_shop`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
INSERT INTO `_DB_PREFIX_loffc_block_item_shop` VALUES
('1','LEO_ID_SHOP'),
('3','LEO_ID_SHOP'),
('14','LEO_ID_SHOP'),
('15','LEO_ID_SHOP'),
('16','LEO_ID_SHOP'),
('17','LEO_ID_SHOP'),
('18','LEO_ID_SHOP'),
('19','LEO_ID_SHOP'),
('21','LEO_ID_SHOP'),
('22','LEO_ID_SHOP'),
('23','LEO_ID_SHOP'),
('24','LEO_ID_SHOP'),
('25','LEO_ID_SHOP'),
('26','LEO_ID_SHOP'),
('29','LEO_ID_SHOP'),
('30','LEO_ID_SHOP'),
('31','LEO_ID_SHOP'),
('32','LEO_ID_SHOP'),
('33','LEO_ID_SHOP'),
('34','LEO_ID_SHOP'),
('35','LEO_ID_SHOP');
CREATE TABLE IF NOT EXISTS `_DB_PREFIX_loffc_block_lang` (
  `id_loffc_block` int(11) NOT NULL,
  `id_lang` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  PRIMARY KEY (`id_loffc_block`,`id_lang`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `_DB_PREFIX_loffc_block_shop` (
  `id_loffc_block` int(11) NOT NULL,
  `id_shop` int(11) NOT NULL,
  PRIMARY KEY (`id_loffc_block`,`id_shop`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
INSERT INTO `_DB_PREFIX_loffc_block_shop` VALUES
('1','LEO_ID_SHOP'),
('2','LEO_ID_SHOP'),
('3','LEO_ID_SHOP'),
('4','LEO_ID_SHOP'),
('13','LEO_ID_SHOP');
";
$dataLang = Array("en"=>"INSERT INTO `_DB_PREFIX_loffc_block_item_lang` VALUES
('1','LEO_ID_LANGUAGE','My orders',''),
('3','LEO_ID_LANGUAGE','Specials',''),
('14','LEO_ID_LANGUAGE','My credit slips',''),
('15','LEO_ID_LANGUAGE','My addresses',''),
('16','LEO_ID_LANGUAGE','My personal info',''),
('17','LEO_ID_LANGUAGE','My vouchers',''),
('18','LEO_ID_LANGUAGE','Delivery',''),
('19','LEO_ID_LANGUAGE','Legal Notice',''),
('21','LEO_ID_LANGUAGE','About us',''),
('22','LEO_ID_LANGUAGE','Secure payment',''),
('23','LEO_ID_LANGUAGE','New products',''),
('24','LEO_ID_LANGUAGE','Best sellers',''),
('25','LEO_ID_LANGUAGE','Our stores',''),
('26','LEO_ID_LANGUAGE','Contact us',''),
('29','LEO_ID_LANGUAGE','About us','<div class=\"box-services\">\r\n<p><img src=\"modules/blockadvfooter/images/logo_footer.png\" alt=\"\" /></p>\r\n<p>Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit.Etiam pharetra, erat sed fermentum feugiat.</p>\r\n</div>'),
('30','LEO_ID_LANGUAGE','Terms and conditions',''),
('31','LEO_ID_LANGUAGE','subscribe us ',''),
('32','LEO_ID_LANGUAGE','Get social','<div class=\"social_footer\">\r\n<p>Sunday when we are open from and dions contact page.</p>\r\n<h3 class=\"title_social\">Get social</h3>\r\n<ul class=\"link_copyright\">\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-facebook\"></em><span>icon-facebook</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-twitter\"></em><span>icon-twitter</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-youtube\"></em><span>icon-youtube</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-google-plus\"></em><span>icon-google-plus</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-linkedin\"></em><span>icon-linkedin</span></a></li>\r\n</ul>\r\n</div>'),
('33','LEO_ID_LANGUAGE','Career Opportunities',''),
('34','LEO_ID_LANGUAGE','Holiday Shop',''),
('35','LEO_ID_LANGUAGE','Shoes and Dresses','');
INSERT INTO `_DB_PREFIX_loffc_block_lang` VALUES
('1','LEO_ID_LANGUAGE','About us'),
('2','LEO_ID_LANGUAGE','Brands'),
('3','LEO_ID_LANGUAGE','Information'),
('4','LEO_ID_LANGUAGE','My account'),
('13','LEO_ID_LANGUAGE','subscribe us');
","de"=>"INSERT INTO `_DB_PREFIX_loffc_block_item_lang` VALUES
('1','LEO_ID_LANGUAGE','My orders',''),
('3','LEO_ID_LANGUAGE','Specials',''),
('14','LEO_ID_LANGUAGE','My credit slips',''),
('15','LEO_ID_LANGUAGE','My addresses',''),
('16','LEO_ID_LANGUAGE','My personal info',''),
('17','LEO_ID_LANGUAGE','My vouchers',''),
('18','LEO_ID_LANGUAGE','Delivery',''),
('19','LEO_ID_LANGUAGE','Legal Notice',''),
('21','LEO_ID_LANGUAGE','About us',''),
('22','LEO_ID_LANGUAGE','Secure payment',''),
('23','LEO_ID_LANGUAGE','New products',''),
('24','LEO_ID_LANGUAGE','Best sellers',''),
('25','LEO_ID_LANGUAGE','Our stores',''),
('26','LEO_ID_LANGUAGE','Contact us',''),
('29','LEO_ID_LANGUAGE','About us','<div class=\"box-services\">\r\n<p><img src=\"modules/blockadvfooter/images/logo_footer.png\" alt=\"\" /></p>\r\n<p>Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit.Etiam pharetra, erat sed fermentum feugiat, velit mauris se in orci enim.</p>\r\n</div>'),
('30','LEO_ID_LANGUAGE','Terms and conditions',''),
('31','LEO_ID_LANGUAGE','subscribe us ',''),
('32','LEO_ID_LANGUAGE','Get social','<div class=\"social_footer\">\r\n<p>Sunday when we are open from and dions contact page.</p>\r\n<h3 class=\"title_social\">Get social</h3>\r\n<ul class=\"link_copyright\">\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-facebook\"></em><span>icon-facebook</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-twitter\"></em><span>icon-twitter</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-youtube\"></em><span>icon-youtube</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-google-plus\"></em><span>icon-google-plus</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-linkedin\"></em><span>icon-linkedin</span></a></li>\r\n</ul>\r\n</div>'),
('33','LEO_ID_LANGUAGE','Career Opportunities',''),
('34','LEO_ID_LANGUAGE','Holiday Shop',''),
('35','LEO_ID_LANGUAGE','Shoes and Dresses','');
INSERT INTO `_DB_PREFIX_loffc_block_lang` VALUES
('1','LEO_ID_LANGUAGE','polnisch'),
('2','LEO_ID_LANGUAGE','Marken'),
('3','LEO_ID_LANGUAGE','Information'),
('4','LEO_ID_LANGUAGE','My account'),
('13','LEO_ID_LANGUAGE','abonneren ons');
","br"=>"INSERT INTO `_DB_PREFIX_loffc_block_item_lang` VALUES
('1','LEO_ID_LANGUAGE','My orders',''),
('3','LEO_ID_LANGUAGE','Specials',''),
('14','LEO_ID_LANGUAGE','My credit slips',''),
('15','LEO_ID_LANGUAGE','My addresses',''),
('16','LEO_ID_LANGUAGE','My personal info',''),
('17','LEO_ID_LANGUAGE','My vouchers',''),
('18','LEO_ID_LANGUAGE','Delivery',''),
('19','LEO_ID_LANGUAGE','Legal Notice',''),
('21','LEO_ID_LANGUAGE','About us',''),
('22','LEO_ID_LANGUAGE','Secure payment',''),
('23','LEO_ID_LANGUAGE','New products',''),
('24','LEO_ID_LANGUAGE','Best sellers',''),
('25','LEO_ID_LANGUAGE','Our stores',''),
('26','LEO_ID_LANGUAGE','Contact us',''),
('29','LEO_ID_LANGUAGE','About us','<div class=\"box-services\">\r\n<p><img src=\"modules/blockadvfooter/images/logo_footer.png\" alt=\"\" /></p>\r\n<p>Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit.Etiam pharetra, erat sed fermentum feugiat, velit mauris se in orci enim.</p>\r\n</div>'),
('30','LEO_ID_LANGUAGE','Terms and conditions',''),
('31','LEO_ID_LANGUAGE','subscribe us ',''),
('32','LEO_ID_LANGUAGE','Get social','<div class=\"social_footer\">\r\n<p>Sunday when we are open from and dions contact page.</p>\r\n<h3 class=\"title_social\">Get social</h3>\r\n<ul class=\"link_copyright\">\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-facebook\"></em><span>icon-facebook</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-twitter\"></em><span>icon-twitter</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-youtube\"></em><span>icon-youtube</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-google-plus\"></em><span>icon-google-plus</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-linkedin\"></em><span>icon-linkedin</span></a></li>\r\n</ul>\r\n</div>'),
('33','LEO_ID_LANGUAGE','Career Opportunities',''),
('34','LEO_ID_LANGUAGE','Holiday Shop',''),
('35','LEO_ID_LANGUAGE','Shoes and Dresses','');
INSERT INTO `_DB_PREFIX_loffc_block_lang` VALUES
('1','LEO_ID_LANGUAGE','polonês'),
('2','LEO_ID_LANGUAGE','Marcas'),
('3','LEO_ID_LANGUAGE','informações'),
('4','LEO_ID_LANGUAGE','My account'),
('13','LEO_ID_LANGUAGE','subscrever-nos');
","es"=>"INSERT INTO `_DB_PREFIX_loffc_block_item_lang` VALUES
('1','LEO_ID_LANGUAGE','My orders',''),
('3','LEO_ID_LANGUAGE','Specials',''),
('14','LEO_ID_LANGUAGE','My credit slips',''),
('15','LEO_ID_LANGUAGE','My addresses',''),
('16','LEO_ID_LANGUAGE','My personal info',''),
('17','LEO_ID_LANGUAGE','My vouchers',''),
('18','LEO_ID_LANGUAGE','Delivery',''),
('19','LEO_ID_LANGUAGE','Legal Notice',''),
('21','LEO_ID_LANGUAGE','About us',''),
('22','LEO_ID_LANGUAGE','Secure payment',''),
('23','LEO_ID_LANGUAGE','New products',''),
('24','LEO_ID_LANGUAGE','Best sellers',''),
('25','LEO_ID_LANGUAGE','Our stores',''),
('26','LEO_ID_LANGUAGE','Contact us',''),
('29','LEO_ID_LANGUAGE','About us','<div class=\"box-services\">\r\n<p><img src=\"modules/blockadvfooter/images/logo_footer.png\" alt=\"\" /></p>\r\n<p>Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit.Etiam pharetra, erat sed fermentum feugiat, velit mauris se in orci enim.</p>\r\n</div>'),
('30','LEO_ID_LANGUAGE','Terms and conditions',''),
('31','LEO_ID_LANGUAGE','subscribe us ',''),
('32','LEO_ID_LANGUAGE','Get social','<div class=\"social_footer\">\r\n<p>Sunday when we are open from and dions contact page.</p>\r\n<h3 class=\"title_social\">Get social</h3>\r\n<ul class=\"link_copyright\">\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-facebook\"></em><span>icon-facebook</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-twitter\"></em><span>icon-twitter</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-youtube\"></em><span>icon-youtube</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-google-plus\"></em><span>icon-google-plus</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-linkedin\"></em><span>icon-linkedin</span></a></li>\r\n</ul>\r\n</div>'),
('33','LEO_ID_LANGUAGE','Career Opportunities',''),
('34','LEO_ID_LANGUAGE','Holiday Shop',''),
('35','LEO_ID_LANGUAGE','Shoes and Dresses','');
INSERT INTO `_DB_PREFIX_loffc_block_lang` VALUES
('1','LEO_ID_LANGUAGE','polaco'),
('2','LEO_ID_LANGUAGE','Marcas'),
('3','LEO_ID_LANGUAGE','información'),
('4','LEO_ID_LANGUAGE','My account'),
('13','LEO_ID_LANGUAGE',' nosotros suscribirse');
","pl"=>"INSERT INTO `_DB_PREFIX_loffc_block_item_lang` VALUES
('1','LEO_ID_LANGUAGE','My orders',''),
('3','LEO_ID_LANGUAGE','Specials',''),
('14','LEO_ID_LANGUAGE','My credit slips',''),
('15','LEO_ID_LANGUAGE','My addresses',''),
('16','LEO_ID_LANGUAGE','My personal info',''),
('17','LEO_ID_LANGUAGE','My vouchers',''),
('18','LEO_ID_LANGUAGE','Delivery',''),
('19','LEO_ID_LANGUAGE','Legal Notice',''),
('21','LEO_ID_LANGUAGE','About us',''),
('22','LEO_ID_LANGUAGE','Secure payment',''),
('23','LEO_ID_LANGUAGE','New products',''),
('24','LEO_ID_LANGUAGE','Best sellers',''),
('25','LEO_ID_LANGUAGE','Our stores',''),
('26','LEO_ID_LANGUAGE','Contact us',''),
('29','LEO_ID_LANGUAGE','About us','<div class=\"box-services\">\r\n<p><img src=\"modules/blockadvfooter/images/logo_footer.png\" alt=\"\" /></p>\r\n<p>Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit.Etiam pharetra, erat sed fermentum feugiat, velit mauris se in orci enim.</p>\r\n</div>'),
('30','LEO_ID_LANGUAGE','Terms and conditions',''),
('31','LEO_ID_LANGUAGE','subscribe us ',''),
('32','LEO_ID_LANGUAGE','Get social','<div class=\"social_footer\">\r\n<p>Sunday when we are open from and dions contact page.</p>\r\n<h3 class=\"title_social\">Get social</h3>\r\n<ul class=\"link_copyright\">\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-facebook\"></em><span>icon-facebook</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-twitter\"></em><span>icon-twitter</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-youtube\"></em><span>icon-youtube</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-google-plus\"></em><span>icon-google-plus</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-linkedin\"></em><span>icon-linkedin</span></a></li>\r\n</ul>\r\n</div>'),
('33','LEO_ID_LANGUAGE','Career Opportunities',''),
('34','LEO_ID_LANGUAGE','Holiday Shop',''),
('35','LEO_ID_LANGUAGE','Shoes and Dresses','');
INSERT INTO `_DB_PREFIX_loffc_block_lang` VALUES
('1','LEO_ID_LANGUAGE','Polski'),
('2','LEO_ID_LANGUAGE','Marki'),
('3','LEO_ID_LANGUAGE','Informacja'),
('4','LEO_ID_LANGUAGE','My account'),
('13','LEO_ID_LANGUAGE','subskrybuj nas');
","ru"=>"INSERT INTO `_DB_PREFIX_loffc_block_item_lang` VALUES
('1','LEO_ID_LANGUAGE','My orders',''),
('3','LEO_ID_LANGUAGE','Specials',''),
('14','LEO_ID_LANGUAGE','My credit slips',''),
('15','LEO_ID_LANGUAGE','My addresses',''),
('16','LEO_ID_LANGUAGE','My personal info',''),
('17','LEO_ID_LANGUAGE','My vouchers',''),
('18','LEO_ID_LANGUAGE','Delivery',''),
('19','LEO_ID_LANGUAGE','Legal Notice',''),
('21','LEO_ID_LANGUAGE','About us',''),
('22','LEO_ID_LANGUAGE','Secure payment',''),
('23','LEO_ID_LANGUAGE','New products',''),
('24','LEO_ID_LANGUAGE','Best sellers',''),
('25','LEO_ID_LANGUAGE','Our stores',''),
('26','LEO_ID_LANGUAGE','Contact us',''),
('29','LEO_ID_LANGUAGE','About us','<div class=\"box-services\">\r\n<p><img src=\"modules/blockadvfooter/images/logo_footer.png\" alt=\"\" /></p>\r\n<p>Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit.Etiam pharetra, erat sed fermentum feugiat, velit mauris se in orci enim.</p>\r\n</div>'),
('30','LEO_ID_LANGUAGE','Terms and conditions',''),
('31','LEO_ID_LANGUAGE','subscribe us ',''),
('32','LEO_ID_LANGUAGE','Get social','<div class=\"social_footer\">\r\n<p>Sunday when we are open from and dions contact page.</p>\r\n<h3 class=\"title_social\">Get social</h3>\r\n<ul class=\"link_copyright\">\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-facebook\"></em><span>icon-facebook</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-twitter\"></em><span>icon-twitter</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-youtube\"></em><span>icon-youtube</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-google-plus\"></em><span>icon-google-plus</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-linkedin\"></em><span>icon-linkedin</span></a></li>\r\n</ul>\r\n</div>'),
('33','LEO_ID_LANGUAGE','Career Opportunities',''),
('34','LEO_ID_LANGUAGE','Holiday Shop',''),
('35','LEO_ID_LANGUAGE','Shoes and Dresses','');
INSERT INTO `_DB_PREFIX_loffc_block_lang` VALUES
('1','LEO_ID_LANGUAGE','О нас'),
('2','LEO_ID_LANGUAGE','Бренды'),
('3','LEO_ID_LANGUAGE','Информация'),
('4','LEO_ID_LANGUAGE','My account'),
('13','LEO_ID_LANGUAGE','подписаться нам');
","it"=>"INSERT INTO `_DB_PREFIX_loffc_block_item_lang` VALUES
('1','LEO_ID_LANGUAGE','My orders',''),
('3','LEO_ID_LANGUAGE','Specials',''),
('14','LEO_ID_LANGUAGE','My credit slips',''),
('15','LEO_ID_LANGUAGE','My addresses',''),
('16','LEO_ID_LANGUAGE','My personal info',''),
('17','LEO_ID_LANGUAGE','My vouchers',''),
('18','LEO_ID_LANGUAGE','Delivery',''),
('19','LEO_ID_LANGUAGE','Legal Notice',''),
('21','LEO_ID_LANGUAGE','About us',''),
('22','LEO_ID_LANGUAGE','Secure payment',''),
('23','LEO_ID_LANGUAGE','New products',''),
('24','LEO_ID_LANGUAGE','Best sellers',''),
('25','LEO_ID_LANGUAGE','Our stores',''),
('26','LEO_ID_LANGUAGE','Contact us',''),
('29','LEO_ID_LANGUAGE','About us','<div class=\"box-services\">\r\n<p><img src=\"modules/blockadvfooter/images/logo_footer.png\" alt=\"\" /></p>\r\n<p>Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit.Etiam pharetra, erat sed fermentum feugiat, velit mauris se in orci enim.</p>\r\n</div>'),
('30','LEO_ID_LANGUAGE','Terms and conditions',''),
('31','LEO_ID_LANGUAGE','subscribe us ',''),
('32','LEO_ID_LANGUAGE','Get social','<div class=\"social_footer\">\r\n<p>Sunday when we are open from and dions contact page.</p>\r\n<h3 class=\"title_social\">Get social</h3>\r\n<ul class=\"link_copyright\">\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-facebook\"></em><span>icon-facebook</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-twitter\"></em><span>icon-twitter</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-youtube\"></em><span>icon-youtube</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-google-plus\"></em><span>icon-google-plus</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-linkedin\"></em><span>icon-linkedin</span></a></li>\r\n</ul>\r\n</div>'),
('33','LEO_ID_LANGUAGE','Career Opportunities',''),
('34','LEO_ID_LANGUAGE','Holiday Shop',''),
('35','LEO_ID_LANGUAGE','Shoes and Dresses','');
INSERT INTO `_DB_PREFIX_loffc_block_lang` VALUES
('1','LEO_ID_LANGUAGE','Chi siamo'),
('2','LEO_ID_LANGUAGE','Marchi'),
('3','LEO_ID_LANGUAGE','informazioni'),
('4','LEO_ID_LANGUAGE','My account'),
('13','LEO_ID_LANGUAGE','noi abbonarsi');
","nl"=>"INSERT INTO `_DB_PREFIX_loffc_block_item_lang` VALUES
('1','LEO_ID_LANGUAGE','My orders',''),
('3','LEO_ID_LANGUAGE','Specials',''),
('14','LEO_ID_LANGUAGE','My credit slips',''),
('15','LEO_ID_LANGUAGE','My addresses',''),
('16','LEO_ID_LANGUAGE','My personal info',''),
('17','LEO_ID_LANGUAGE','My vouchers',''),
('18','LEO_ID_LANGUAGE','Delivery',''),
('19','LEO_ID_LANGUAGE','Legal Notice',''),
('21','LEO_ID_LANGUAGE','About us',''),
('22','LEO_ID_LANGUAGE','Secure payment',''),
('23','LEO_ID_LANGUAGE','New products',''),
('24','LEO_ID_LANGUAGE','Best sellers',''),
('25','LEO_ID_LANGUAGE','Our stores',''),
('26','LEO_ID_LANGUAGE','Contact us',''),
('29','LEO_ID_LANGUAGE','About us','<div class=\"box-services\">\r\n<p><img src=\"modules/blockadvfooter/images/logo_footer.png\" alt=\"\" /></p>\r\n<p>Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit.Etiam pharetra, erat sed fermentum feugiat, velit mauris se in orci enim.</p>\r\n</div>'),
('30','LEO_ID_LANGUAGE','Terms and conditions',''),
('31','LEO_ID_LANGUAGE','subscribe us ',''),
('32','LEO_ID_LANGUAGE','Get social','<div class=\"social_footer\">\r\n<p>Sunday when we are open from and dions contact page.</p>\r\n<h3 class=\"title_social\">Get social</h3>\r\n<ul class=\"link_copyright\">\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-facebook\"></em><span>icon-facebook</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-twitter\"></em><span>icon-twitter</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-youtube\"></em><span>icon-youtube</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-google-plus\"></em><span>icon-google-plus</span></a></li>\r\n<li><a class=\"item-icon-list\" href=\"#\"><em class=\"fa fa-linkedin\"></em><span>icon-linkedin</span></a></li>\r\n</ul>\r\n</div>'),
('33','LEO_ID_LANGUAGE','Career Opportunities',''),
('34','LEO_ID_LANGUAGE','Holiday Shop',''),
('35','LEO_ID_LANGUAGE','Shoes and Dresses','');
INSERT INTO `_DB_PREFIX_loffc_block_lang` VALUES
('1','LEO_ID_LANGUAGE','over ons'),
('2','LEO_ID_LANGUAGE','Nederlands'),
('3','LEO_ID_LANGUAGE','informatie'),
('4','LEO_ID_LANGUAGE','My account'),
('13','LEO_ID_LANGUAGE','abonneren ons');
");